version: "3.3"
services:
  stream-in:
    environment:
      - PORT=5005
      - DELAY                # Supply in run script
      - SUFFIX=id_str
      - OUTPUT_FILE=/in.csv
      - DURATION             # Supply in run script
      - NEXTCLOUD_URL=https://cloud.ilabt.imec.be/remote.php/webdav/
      - NEXTCLOUD_USERNAME   # Supply in .env
      - NEXTCLOUD_PASSWORD   # Supply in .env
      - NEXTCLOUD_DIRECTORY  # Supply in run script
      - NEXTCLOUD_INPUT_FILE # Supply in run script
    build: ./stream-in
    #ports:
    #  - "5005:5005"
    expose:
      - 5005
    networks:
      - benchmark

networks:
  benchmark:
