apiVersion: v1
kind: Service
metadata:
  labels:
    app: jobmanager
  name: jobmanager
spec:
  ports:
  - name: "6123"
    port: 6123
  - name: "6124"
    port: 6124
  - name: "8081"
    port: 8081  
  selector:
    app: jobmanager
