apiVersion: v1
kind: Service
metadata:
  labels:
    app: stream-out
  name: stream-out
spec:
  ports:
  - name: "9999"
    port: 9999
  - name: "3000"
    port: 3000  
  selector:
    app: stream-out
