apiVersion: v1
kind: Service
metadata:
  labels:
    app: taskmanager
  name: taskmanager
spec:
  ports:
  - name: "6121"
    port: 6121
  - name: "6122"
    port: 6122  
  selector:
    app: taskmanager
